,# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [3]:
print("Hello World!")


Hello World!


In [5]:
x=3


In [7]:
import module_1

liste_1 = module_1.fibonacci(50)

In [8]:
liste_1

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [6]:
x

3

In [9]:
import random
import statistics

print(statistics.mean(liste_1))
print(statistics.variance(liste_1))

print(random.choice(['jean', 'george','Marie']))
print(random.randint(0,5))
print(random.sample(liste_1,random.randrange(10)))


8.8
121.73333333333333
jean
5
[3, 21, 34, 2, 5]


In [11]:
liste_1 = module_1.fibonacci(50)

In [13]:
import os

os.getcwd() #current working direction

'C:\\Users\\pamel\\Python_MachineLearning'

In [15]:
import glob

glob.glob("*")

['anaconda_projects',
 'data',
 'models',
 'module_1.py',
 'module_2.py',
 'README.md',
 'requirements.txt',
 'sample.ipynb',
 '__pycache__']

In [4]:
import numpy as np

np.array([1,2,3])

array([1, 2, 3])

In [5]:
B = np.zeros((3,2))
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
B.shape


(3, 2)

In [7]:
C = np.ones((3,2))
C

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
D = np.full((3,2), 9)
D

array([[9, 9],
       [9, 9],
       [9, 9]])

In [16]:
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [17]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
np.arange(0,10,0.7)

array([0.])

In [47]:
A = np.zeros((3,2))
B = np.ones((3,2))
A

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
C=np.hstack((A,B))
C

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [28]:
D = np.vstack((A,B))
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.concatenate((A,B), axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [34]:
D = D.reshape((3,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [43]:
A = A.reshape((A.shape[0],1))
A

array([[1],
       [2],
       [3]])

In [38]:
D.ravel().shape

(12,)

In [48]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
A[1,1]

np.int64(5)

In [57]:
A[:,1]

array([2, 5, 8])

In [61]:
A[0:2,0:2] = 10
A

array([[10, 10,  3],
       [10, 10,  6],
       [ 7,  8,  9]])

In [62]:
A[:,1:]

array([[10,  3],
       [10,  6],
       [ 8,  9]])

In [63]:
A[:,-2:]

array([[10,  3],
       [10,  6],
       [ 8,  9]])

In [64]:
B = np.zeros((4,4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
B[1:3,1:3] = 1
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [66]:
C = np.zeros((5,5))
C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
C[::2,::2] = 1
C

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

In [69]:
A = np.random.randint(0,10,[5,5])
A

array([[8, 1, 5, 9, 8],
       [9, 4, 3, 0, 3],
       [5, 0, 2, 3, 8],
       [1, 3, 3, 3, 7],
       [0, 1, 9, 9, 0]], dtype=int32)

In [73]:
A[A<5].shape


(0,)